complete header and css box #3
DatWithTheWorld/Practice_html_css_2 pull request #6
Opened 2023-11-21 13:34 UTC by DatWithTheWorld

Desktop: 
![image](https://github.com/DatWithTheWorld/Practice_html_css_2/assets/131734339/0f4aece1-cb0f-4612-be09-52d98e891e89)

2023-11-21 14:01 UTC, xuanquocc commented on src/layouts/header.html
> +<<<<<<< Updated upstream
clear this

2023-11-21 14:02 UTC, xuanquocc commented on src/stylesheets/components/_index.scss
> +>>>>>>> Stashed changes
clear this

2023-11-21 14:02 UTC, xuanquocc requested changes
end of lines

2023-12-01 09:53 UTC, baonguyen26 commented on src/components/box.html
> +            <figure class="image">
Why did you change the code here?

2023-12-01 13:10 UTC, merged